name: portfolio

services:
  portfolio-webapp:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "1"
    container_name: portfolio-webapp
    restart: unless-stopped
    ports:
      - "10580:80"
    mem_limit: 512m
    cpus: 0.5
    memswap_limit: 768m
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.portfolio-webapp-web.rule=Host(`litwa.dev`)
      - traefik.http.routers.portfolio-webapp-web.entrypoints=web
      - traefik.http.services.portfolio-webapp-web.loadbalancer.server.port=80
      - traefik.http.routers.portfolio-webapp-web.service=portfolio-webapp-web
      - traefik.http.routers.portfolio-webapp-websecure.rule=Host(`litwa.dev`)
      - traefik.http.routers.portfolio-webapp-websecure.entrypoints=websecure
      - traefik.http.services.portfolio-webapp-websecure.loadbalancer.server.port=80
      - traefik.http.routers.portfolio-webapp-websecure.service=portfolio-webapp-websecure
      - traefik.http.routers.portfolio-webapp-websecure.tls.certresolver=letsencrypt
    networks:
      - shared-network
      - dokploy-network

networks:
  shared-network:
    external: true
  dokploy-network:
    external: true
